-- 065_bootstrap_core_schema.sql
-- CANON BOOTSTRAP: reproduce el esquema del RDS (tablas/columnas/tipos/defaults).
-- Nota: es "create-if-missing". Si una tabla ya existe con otro esquema, Postgres no la reescribe.

BEGIN;

-- Extensiones
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enums presentes en el esquema (según dump / modelos)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_contents_content_type') THEN
    CREATE TYPE public.enum_contents_content_type AS ENUM ('text_image', 'image_text', 'just_image', 'just_text');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_banners_position_type') THEN
    CREATE TYPE public.enum_banners_position_type AS ENUM ('right', 'top', 'medium');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_banners_page_type') THEN
    CREATE TYPE public.enum_banners_page_type AS ENUM ('home', 'custom');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'media_type') THEN
    CREATE TYPE public.media_type AS ENUM ('pdf', 'image');
  END IF;
END $$;

-- portals (canonical table name portals_id)
CREATE TABLE IF NOT EXISTS public.portals_id (
  portal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portal_name VARCHAR(255) NOT NULL,
  portal_name_key VARCHAR(255) NOT NULL,
  portal_domain VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  portal_default_locale VARCHAR(255) NOT NULL DEFAULT 'es'::character varying,
  portal_theme VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  portal_created_at TIMESTAMPTZ NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS portals_id_portal_name_key_idx ON public.portals_id (portal_name_key);
CREATE INDEX IF NOT EXISTS portals_id_portal_domain_idx ON public.portals_id (portal_domain);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_company_portals_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.company_portal_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_contact_comments_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.contact_comment_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_event_portals_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.event_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_event_articles_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.event_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_events_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.event_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_default_portal_id()
RETURNS INTEGER
LANGUAGE sql
STABLE
AS $$
  SELECT portal_id FROM public.portals_id ORDER BY portal_created_at ASC NULLS LAST, portal_id ASC LIMIT 1;
$$;

-- 2) users_db (esquema final + array relaciones)
CREATE TABLE IF NOT EXISTS public.users_db (
  user_id UUID NOT NULL,
  user_email VARCHAR(255) NOT NULL,
  user_name VARCHAR(255) NULL,
  user_surnames VARCHAR(255) NULL,
  user_description TEXT NULL,
  user_main_image_src VARCHAR(255) NULL,
  user_preferences JSONB NULL,
  user_cognito_sub VARCHAR(255) NULL,
  user_linkedin_profile VARCHAR(255) NULL,
  user_employee_relations_array TEXT[] NOT NULL DEFAULT '{}'::text[],
  newsletter_user_lists_id_array UUID[] NOT NULL DEFAULT '{}'::uuid[],
  CONSTRAINT users_db_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_db_user_email_key UNIQUE (user_email)
);

-- 3) companies_db (esquema final + array relaciones)
CREATE TABLE IF NOT EXISTS public.companies_db (
  company_id VARCHAR(255) NOT NULL,
  company_commercial_name VARCHAR(255) NOT NULL,
  company_country VARCHAR(255) NULL DEFAULT ''::character varying,
  company_category VARCHAR(255) NULL DEFAULT ''::character varying,
  company_main_description TEXT NULL DEFAULT ''::text,
  company_main_image VARCHAR(255) NULL DEFAULT ''::character varying,
  company_main_telephone VARCHAR(255) NULL DEFAULT ''::character varying,
  company_full_address VARCHAR(255) NULL DEFAULT ''::character varying,
  company_web_link VARCHAR(255) NULL DEFAULT ''::character varying,
  company_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  company_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  company_employee_relations_array TEXT[] NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT companies_db_pkey PRIMARY KEY (company_id)
);

CREATE INDEX IF NOT EXISTS companies_db_commercial_name_idx ON public.companies_db (company_commercial_name);
CREATE INDEX IF NOT EXISTS companies_db_country_idx ON public.companies_db (company_country);
CREATE INDEX IF NOT EXISTS companies_db_category_idx ON public.companies_db (company_category);

CREATE OR REPLACE FUNCTION public.set_companies_db_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.company_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS companies_db_updated_at ON public.companies_db;
CREATE TRIGGER companies_db_updated_at
  BEFORE UPDATE ON public.companies_db
  FOR EACH ROW EXECUTE FUNCTION public.set_companies_db_updated_at();

-- 4) products_db (esquema final)
CREATE TABLE IF NOT EXISTS public.products_db (
  product_id VARCHAR(255) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  product_price NUMERIC NOT NULL DEFAULT 0,
  company_id VARCHAR(255) NULL DEFAULT ''::character varying,
  product_description TEXT NULL DEFAULT ''::text,
  product_main_image_src VARCHAR(255) NULL DEFAULT ''::character varying,
  product_categories_array VARCHAR(255)[] NULL DEFAULT (ARRAY[]::character varying[])::character varying(255)[],
  product_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  product_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT products_db_pkey PRIMARY KEY (product_id)
);

CREATE INDEX IF NOT EXISTS products_db_product_name_idx ON public.products_db (product_name);
CREATE INDEX IF NOT EXISTS products_db_company_id_idx ON public.products_db (company_id);

CREATE OR REPLACE FUNCTION public.set_products_db_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.product_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS products_db_updated_at ON public.products_db;
CREATE TRIGGER products_db_updated_at
  BEFORE UPDATE ON public.products_db
  FOR EACH ROW EXECUTE FUNCTION public.set_products_db_updated_at();

-- 5) company_portals (tabla puente)
CREATE TABLE IF NOT EXISTS public.company_portals (
  company_portal_id UUID NOT NULL DEFAULT gen_random_uuid(),
  company_id TEXT NOT NULL,
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE CASCADE,
  company_portal_slug TEXT NOT NULL,
  company_portal_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  company_portal_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT company_portals_pkey PRIMARY KEY (company_portal_id),
  CONSTRAINT company_portals_company_id_portal_id_key UNIQUE (company_id, portal_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS company_portals_portal_slug_uidx ON public.company_portals (portal_id, company_portal_slug);

DROP TRIGGER IF EXISTS company_portals_updated_at ON public.company_portals;
CREATE TRIGGER company_portals_updated_at
  BEFORE UPDATE ON public.company_portals
  FOR EACH ROW EXECUTE FUNCTION public.set_company_portals_updated_at();

-- 6) product_portals (orden de columnas como en RDS; product_portal_id nullable en catálogo legacy)
CREATE TABLE IF NOT EXISTS public.product_portals (
  product_id TEXT NOT NULL,
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE CASCADE,
  product_slug TEXT NOT NULL,
  product_status TEXT NOT NULL DEFAULT 'active'::text,
  product_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  product_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  product_portal_id UUID NULL DEFAULT gen_random_uuid(),
  CONSTRAINT product_portals_pkey PRIMARY KEY (product_id, portal_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS product_portals_portal_product_slug_uidx ON public.product_portals (portal_id, product_slug);

CREATE OR REPLACE FUNCTION public.set_product_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.product_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS product_portals_updated_at ON public.product_portals;
CREATE TRIGGER product_portals_updated_at
  BEFORE UPDATE ON public.product_portals
  FOR EACH ROW EXECUTE FUNCTION public.set_product_updated_at();

-- 7) employee_relations (tabla final)
CREATE TABLE IF NOT EXISTS public.employee_relations (
  employee_rel_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_user_id UUID NOT NULL REFERENCES public.users_db(user_id) ON DELETE CASCADE,
  employee_company_id VARCHAR(255) NOT NULL REFERENCES public.companies_db(company_id) ON DELETE CASCADE,
  employee_role VARCHAR(255) NOT NULL DEFAULT 'employee'::character varying,
  employee_rel_status VARCHAR(32) NOT NULL DEFAULT 'active',
  employee_rel_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  employee_rel_end_date DATE NULL
);

CREATE INDEX IF NOT EXISTS employee_relations_user_idx ON public.employee_relations (employee_user_id);
CREATE INDEX IF NOT EXISTS employee_relations_company_idx ON public.employee_relations (employee_company_id);
CREATE INDEX IF NOT EXISTS employee_relations_status_idx ON public.employee_relations (employee_rel_status);
CREATE INDEX IF NOT EXISTS employee_relations_company_status_idx ON public.employee_relations (employee_company_id, employee_rel_status);
CREATE UNIQUE INDEX IF NOT EXISTS employee_relations_user_company_role_start_uidx
  ON public.employee_relations (employee_user_id, employee_company_id, employee_role, employee_rel_start_date);

CREATE TABLE IF NOT EXISTS public.company_administrators (
  company_administrator_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users_db (user_id) ON DELETE CASCADE,
  company_id VARCHAR(255) NOT NULL REFERENCES public.companies_db (company_id) ON DELETE CASCADE,
  company_administrator_role_name VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  employee_admission_rights BOOLEAN NOT NULL DEFAULT FALSE,
  employee_deletion_rights BOOLEAN NOT NULL DEFAULT FALSE,
  employee_modification_rights BOOLEAN NOT NULL DEFAULT FALSE,
  base_role_modification_rights BOOLEAN NOT NULL DEFAULT FALSE,
  admin_role_modification_rights BOOLEAN NOT NULL DEFAULT FALSE,
  product_addition_rights BOOLEAN NOT NULL DEFAULT FALSE,
  product_modification_rights BOOLEAN NOT NULL DEFAULT FALSE,
  product_deletion_rights BOOLEAN NOT NULL DEFAULT FALSE,
  base_company_data_modification_rights BOOLEAN NOT NULL DEFAULT FALSE,
  advanced_company_data_modification_rights BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT company_administrators_pkey PRIMARY KEY (company_administrator_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS company_administrators_user_company_uidx
  ON public.company_administrators (user_id, company_id);
CREATE INDEX IF NOT EXISTS company_administrators_company_id_idx ON public.company_administrators (company_id);
CREATE INDEX IF NOT EXISTS company_administrators_user_id_idx ON public.company_administrators (user_id);

-- 8) company_categories + puente a portals
CREATE TABLE IF NOT EXISTS public.company_categories (
  category_id VARCHAR(32) PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL,
  category_description TEXT NULL DEFAULT ''::text,
  category_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  category_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS company_categories_name_lower_uidx
  ON public.company_categories (LOWER(category_name));
CREATE INDEX IF NOT EXISTS company_categories_name_idx
  ON public.company_categories (category_name);

CREATE TABLE IF NOT EXISTS public.company_categories_portal (
  category_portal_relation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id VARCHAR(32) NOT NULL REFERENCES public.company_categories(category_id) ON DELETE CASCADE,
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS company_categories_portal_uidx
  ON public.company_categories_portal (category_id, portal_id);
CREATE INDEX IF NOT EXISTS company_categories_portal_portal_idx
  ON public.company_categories_portal (portal_id);

-- 9) portal_banners (tabla final)
CREATE TABLE IF NOT EXISTS public.portal_banners (
  id_banner VARCHAR(255) NOT NULL,
  banner_image_src VARCHAR(255) NOT NULL,
  banner_route VARCHAR(255) NOT NULL DEFAULT '/'::character varying,
  banner_redirection_url VARCHAR(255) NOT NULL DEFAULT 'https://www.vidrioperfil.com'::character varying,
  banner_position_type public.enum_banners_position_type NOT NULL,
  banner_page_type public.enum_banners_page_type NOT NULL,
  banner_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  banner_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE CASCADE,
  alt TEXT NULL,
  starts_at TIMESTAMPTZ NULL,
  ends_at TIMESTAMPTZ NULL,
  position INTEGER NOT NULL DEFAULT 0,
  banner_appearence_weight INTEGER NOT NULL DEFAULT 2,
  banner_starting_date DATE NOT NULL DEFAULT CURRENT_DATE,
  banner_ending_date DATE NOT NULL DEFAULT ((CURRENT_DATE + '1 year'::interval))::date,
  banner_position INTEGER NOT NULL DEFAULT 0,
  banner_status VARCHAR(32) NOT NULL DEFAULT 'published'::character varying,
  CONSTRAINT portal_banners_pkey PRIMARY KEY (id_banner)
);

CREATE OR REPLACE FUNCTION public.set_portal_banners_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.banner_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS portal_banners_updated_at ON public.portal_banners;
CREATE TRIGGER portal_banners_updated_at
  BEFORE UPDATE ON public.portal_banners
  FOR EACH ROW EXECUTE FUNCTION public.set_portal_banners_updated_at();

CREATE INDEX IF NOT EXISTS portal_banners_portal_page_route_idx
  ON public.portal_banners (portal_id, banner_page_type, banner_route);
CREATE INDEX IF NOT EXISTS portal_banners_portal_slot_position_idx
  ON public.portal_banners (portal_id, banner_page_type, banner_route, banner_position_type, banner_position);
CREATE INDEX IF NOT EXISTS portal_banners_portal_dates_idx
  ON public.portal_banners (portal_id, banner_starting_date, banner_ending_date);

-- ===== Canon purge: legacy tables that must not exist =====
DROP TABLE IF EXISTS public.company_members CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ===== Articles (canon: articles_db, article_portals, article_contents, article_comments) =====

CREATE TABLE IF NOT EXISTS public.articles_db (
  id_article VARCHAR(255) NOT NULL,
  article_title VARCHAR(255) NOT NULL,
  article_subtitle VARCHAR(255) NULL,
  article_main_image_url VARCHAR(255) NULL,
  article_date TIMESTAMPTZ NOT NULL,
  article_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  article_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  article_highlited_position TEXT NULL,
  is_article_event BOOLEAN NOT NULL DEFAULT false,
  article_event_id VARCHAR(255) NULL DEFAULT ''::character varying,
  article_company_names_array TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
  article_company_id_array TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
  CONSTRAINT articles_db_pkey PRIMARY KEY (id_article)
);

CREATE INDEX IF NOT EXISTS articles_db_article_title_idx ON public.articles_db (article_title);
CREATE INDEX IF NOT EXISTS articles_db_article_date_idx ON public.articles_db (article_date);
CREATE INDEX IF NOT EXISTS articles_db_is_article_event_idx ON public.articles_db (is_article_event);
CREATE INDEX IF NOT EXISTS articles_db_article_event_id_idx ON public.articles_db (article_event_id);

CREATE OR REPLACE FUNCTION public.set_articles_db_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.article_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS articles_db_updated_at ON public.articles_db;
CREATE TRIGGER articles_db_updated_at
  BEFORE UPDATE ON public.articles_db
  FOR EACH ROW EXECUTE FUNCTION public.set_articles_db_updated_at();

CREATE TABLE IF NOT EXISTS public.article_portals (
  article_portals_id UUID NOT NULL DEFAULT gen_random_uuid(),
  article_id TEXT NOT NULL REFERENCES public.articles_db(id_article) ON DELETE CASCADE,
  article_portal_ref_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE CASCADE,
  article_slug TEXT NOT NULL,
  article_status TEXT NOT NULL DEFAULT 'draft'::text,
  article_published_at TIMESTAMPTZ NULL,
  article_visibility TEXT NOT NULL DEFAULT 'public'::text,
  article_highlight_position TEXT NULL,
  article_commenting_enabled BOOLEAN NOT NULL DEFAULT true,
  article_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  article_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
  ,
  CONSTRAINT article_portals_pkey PRIMARY KEY (article_portals_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS article_portals_ref_slug_uidx
  ON public.article_portals (article_portal_ref_id, article_slug);
CREATE INDEX IF NOT EXISTS article_portals_ref_status_published_idx
  ON public.article_portals (article_portal_ref_id, article_status, article_published_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS article_portals_article_id_idx
  ON public.article_portals (article_id);

CREATE OR REPLACE FUNCTION public.set_article_portals_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.article_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS article_portals_updated_at ON public.article_portals;
CREATE TRIGGER article_portals_updated_at
  BEFORE UPDATE ON public.article_portals
  FOR EACH ROW EXECUTE FUNCTION public.set_article_portals_updated_at();

CREATE TABLE IF NOT EXISTS public.article_contents (
  article_content_id VARCHAR(255) NOT NULL,
  article_content_type public.enum_contents_content_type NOT NULL,
  article_content_content JSONB NOT NULL,
  article_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  article_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  article_id TEXT NOT NULL REFERENCES public.articles_db(id_article) ON DELETE CASCADE,
  article_content_position INTEGER NOT NULL,
  CONSTRAINT article_contents_pkey PRIMARY KEY (article_content_id)
);

CREATE INDEX IF NOT EXISTS article_contents_type_idx ON public.article_contents (article_content_type);
CREATE INDEX IF NOT EXISTS article_contents_article_pos_idx ON public.article_contents (article_id, article_content_position);

CREATE OR REPLACE FUNCTION public.set_article_contents_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.article_updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS article_contents_updated_at ON public.article_contents;
CREATE TRIGGER article_contents_updated_at
  BEFORE UPDATE ON public.article_contents
  FOR EACH ROW EXECUTE FUNCTION public.set_article_contents_updated_at();

CREATE TABLE IF NOT EXISTS public.article_comments (
  article_comment_id VARCHAR(255) NOT NULL,
  article_comment_timestamp TIMESTAMPTZ NOT NULL,
  article_comment_user_id UUID NULL REFERENCES public.users_db(user_id) ON DELETE SET NULL,
  article_comment_content TEXT NOT NULL,
  article_portals_id UUID NOT NULL REFERENCES public.article_portals(article_portals_id) ON DELETE CASCADE
  ,
  CONSTRAINT article_comments_pkey PRIMARY KEY (article_comment_id)
);

CREATE INDEX IF NOT EXISTS article_comments_portal_ts_idx
  ON public.article_comments (article_portals_id, article_comment_timestamp DESC);
CREATE INDEX IF NOT EXISTS article_comments_user_idx
  ON public.article_comments (article_comment_user_id);

-- ===== Events =====
CREATE TABLE IF NOT EXISTS public.events (
  event_id VARCHAR(255) NOT NULL,
  event_name VARCHAR(255) NOT NULL,
  event_country VARCHAR(255) NULL DEFAULT ''::character varying,
  event_location VARCHAR(255) NULL DEFAULT ''::character varying,
  event_main_description TEXT NULL DEFAULT ''::text,
  event_region VARCHAR(255) NULL DEFAULT ''::character varying,
  event_start_date DATE NOT NULL,
  event_end_date DATE NOT NULL,
  event_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_main_image_src VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_id VARCHAR(255) NULL DEFAULT NULL::character varying,
  CONSTRAINT events_pkey PRIMARY KEY (event_id)
);

CREATE INDEX IF NOT EXISTS events_event_name_idx ON public.events (event_name);
CREATE INDEX IF NOT EXISTS events_start_date_idx ON public.events (event_start_date);
CREATE INDEX IF NOT EXISTS events_region_idx ON public.events (event_region);

DROP TRIGGER IF EXISTS events_updated_at ON public.events;
CREATE TRIGGER events_updated_at
  BEFORE UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION public.set_events_updated_at();

CREATE TABLE IF NOT EXISTS public.event_portals (
  event_portal_id UUID NOT NULL DEFAULT gen_random_uuid(),
  event_id TEXT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE CASCADE,
  event_portal_slug TEXT NOT NULL,
  event_portal_status TEXT NOT NULL DEFAULT 'active',
  event_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_portals_pkey PRIMARY KEY (event_portal_id),
  CONSTRAINT event_portals_event_id_portal_id_key UNIQUE (event_id, portal_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS event_portals_portal_slug_uidx ON public.event_portals (portal_id, event_portal_slug);
DROP TRIGGER IF EXISTS event_portals_updated_at ON public.event_portals;
CREATE TRIGGER event_portals_updated_at
  BEFORE UPDATE ON public.event_portals
  FOR EACH ROW EXECUTE FUNCTION public.set_event_portals_updated_at();

CREATE TABLE IF NOT EXISTS public.event_articles (
  event_article_id UUID NOT NULL DEFAULT gen_random_uuid(),
  event_id TEXT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
  article_id TEXT NOT NULL REFERENCES public.articles_db(id_article) ON DELETE CASCADE,
  position INTEGER NULL,
  event_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_articles_pkey PRIMARY KEY (event_article_id),
  CONSTRAINT event_articles_event_id_article_id_key UNIQUE (event_id, article_id)
);

DROP TRIGGER IF EXISTS event_articles_updated_at ON public.event_articles;
CREATE TRIGGER event_articles_updated_at
  BEFORE UPDATE ON public.event_articles
  FOR EACH ROW EXECUTE FUNCTION public.set_event_articles_updated_at();

-- ===== Publications =====
CREATE TABLE IF NOT EXISTS public.publications_db (
  publication_id VARCHAR(255) NOT NULL,
  magazine_id VARCHAR(255) NULL,
  magazine_general_issue_number INTEGER NULL,
  publication_year INTEGER NULL,
  magazine_this_year_issue INTEGER NULL,
  publication_expected_publication_month SMALLINT NULL,
  real_publication_month_date DATE NULL,
  publication_materials_deadline DATE NULL,
  publication_main_image_url VARCHAR(512) NULL,
  publication_edition_name VARCHAR(255) NULL DEFAULT ''::character varying,
  is_special_edition BOOLEAN NOT NULL DEFAULT FALSE,
  publication_theme VARCHAR(255) NULL DEFAULT ''::character varying,
  publication_status VARCHAR(64) NOT NULL DEFAULT 'draft'::character varying,
  publication_format VARCHAR(32) NOT NULL DEFAULT 'flipbook'::character varying,
  CONSTRAINT publications_db_pkey PRIMARY KEY (publication_id),
  CONSTRAINT publications_db_publication_format_check CHECK (publication_format IN ('flipbook', 'informer'))
);

CREATE INDEX IF NOT EXISTS publications_db_magazine_id_idx ON public.publications_db (magazine_id);
CREATE INDEX IF NOT EXISTS publications_db_publication_year_idx ON public.publications_db (publication_year);
CREATE INDEX IF NOT EXISTS publications_db_publication_status_idx ON public.publications_db (publication_status);
CREATE INDEX IF NOT EXISTS publications_db_real_pub_date_idx ON public.publications_db (real_publication_month_date);

-- ===== Mediateca (FolderModel / MediaModel) =====
CREATE TABLE IF NOT EXISTS public.mediateca_folders (
  mediateca_folder_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mediateca_folder_name VARCHAR(255) NOT NULL,
  mediateca_parent_folder_id UUID NULL REFERENCES public.mediateca_folders(mediateca_folder_id),
  mediateca_folder_created_at TIMESTAMPTZ NULL DEFAULT now(),
  mediateca_folder_updated_at TIMESTAMPTZ NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mediateca_folders_parent_idx ON public.mediateca_folders (mediateca_parent_folder_id);

CREATE TABLE IF NOT EXISTS public.mediateca_media_contents (
  mediateca_content_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  mediateca_folder_id UUID NULL REFERENCES public.mediateca_folders(mediateca_folder_id),
  mediateca_content_name VARCHAR(255) NOT NULL,
  mediateca_content_src TEXT NULL,
  mediateca_s3_key TEXT NOT NULL UNIQUE,
  content_mime_type VARCHAR(255) NULL,
  mediateca_content_type public.media_type NOT NULL,
  mediateca_content_created_at TIMESTAMPTZ NULL DEFAULT now(),
  mediateca_content_updated_at TIMESTAMPTZ NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mediateca_media_contents_folder_idx ON public.mediateca_media_contents (mediateca_folder_id);
CREATE INDEX IF NOT EXISTS mediateca_media_contents_type_idx ON public.mediateca_media_contents (mediateca_content_type);
CREATE INDEX IF NOT EXISTS mediateca_media_contents_created_at_idx ON public.mediateca_media_contents (mediateca_content_created_at);

-- ===== CRM / Admin DBs (CustomerDbModel / ContactDbModel / AgentDbModel) =====
CREATE TABLE IF NOT EXISTS public.customers_db (
  customer_id VARCHAR(255) PRIMARY KEY,
  customer_account_name VARCHAR(512) NOT NULL,
  customer_tax_id VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_country VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_full_address TEXT NULL DEFAULT ''::text,
  customer_main_phone VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_main_email VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_website VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_industry VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_agent_id VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_status VARCHAR(255) NULL DEFAULT 'active'::character varying,
  customer_tags TEXT[] NULL DEFAULT '{}'::text[],
  customer_related_accounts TEXT[] NULL DEFAULT '{}'::text[],
  customer_company_id_array TEXT[] NULL DEFAULT '{}'::text[],
  customer_product_id_array TEXT[] NULL DEFAULT '{}'::text[],
  customer_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  customer_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customers_db_account_name_idx ON public.customers_db (customer_account_name);
CREATE INDEX IF NOT EXISTS customers_db_country_idx ON public.customers_db (customer_country);
CREATE INDEX IF NOT EXISTS customers_db_status_idx ON public.customers_db (customer_status);
CREATE INDEX IF NOT EXISTS customers_db_agent_id_idx ON public.customers_db (customer_agent_id);

CREATE TABLE IF NOT EXISTS public.contacts_db (
  contact_id VARCHAR(255) PRIMARY KEY,
  contact_name VARCHAR(255) NOT NULL,
  contact_surnames VARCHAR(255) NULL DEFAULT ''::character varying,
  contact_role VARCHAR(255) NULL DEFAULT ''::character varying,
  contact_email VARCHAR(255) NULL DEFAULT ''::character varying,
  contact_phone VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_id VARCHAR(255) NULL DEFAULT ''::character varying,
  customer_company_name VARCHAR(255) NULL DEFAULT ''::character varying,
  contact_user_id_array TEXT[] NULL DEFAULT '{}'::text[],
  contact_linkedin_url VARCHAR(255) NULL DEFAULT ''::character varying,
  contact_based_in_country VARCHAR(255) NULL DEFAULT ''::character varying,
  contact_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  contact_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contacts_db_contact_name_idx ON public.contacts_db (contact_name);
CREATE INDEX IF NOT EXISTS contacts_db_customer_id_idx ON public.contacts_db (customer_id);
CREATE INDEX IF NOT EXISTS contacts_db_contact_email_idx ON public.contacts_db (contact_email);
CREATE INDEX IF NOT EXISTS contacts_db_customer_company_name_idx ON public.contacts_db (customer_company_name);

CREATE TABLE IF NOT EXISTS public.contact_comments (
  contact_comment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id VARCHAR(255) NOT NULL REFERENCES public.contacts_db(contact_id) ON DELETE CASCADE,
  agent_id VARCHAR(255) NULL REFERENCES public.agents_db(agent_id) ON DELETE SET NULL,
  contact_comment_content TEXT NOT NULL DEFAULT ''::text,
  contact_comment_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  contact_comment_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contact_comments_contact_id_idx ON public.contact_comments (contact_id);
CREATE INDEX IF NOT EXISTS contact_comments_agent_id_idx ON public.contact_comments (agent_id);
DROP TRIGGER IF EXISTS contact_comments_updated_at ON public.contact_comments;
CREATE TRIGGER contact_comments_updated_at
  BEFORE UPDATE ON public.contact_comments
  FOR EACH ROW EXECUTE FUNCTION public.set_contact_comments_updated_at();

-- customers_db comments
CREATE OR REPLACE FUNCTION public.set_customer_comments_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.customer_comment_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.customer_comments (
  customer_comment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id VARCHAR(255) NOT NULL REFERENCES public.customers_db(customer_id) ON DELETE CASCADE,
  agent_id VARCHAR(255) NULL REFERENCES public.agents_db(agent_id) ON DELETE SET NULL,
  customer_comment_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  customer_comment_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customer_comments_customer_id_idx ON public.customer_comments (customer_id);
CREATE INDEX IF NOT EXISTS customer_comments_agent_id_idx ON public.customer_comments (agent_id);

DROP TRIGGER IF EXISTS customer_comments_updated_at ON public.customer_comments;
CREATE TRIGGER customer_comments_updated_at
  BEFORE UPDATE ON public.customer_comments
  FOR EACH ROW EXECUTE FUNCTION public.set_customer_comments_updated_at();

CREATE TABLE IF NOT EXISTS public.agents_db (
  agent_id VARCHAR(255) PRIMARY KEY,
  agent_name VARCHAR(255) NOT NULL,
  agent_email VARCHAR(255) NULL DEFAULT ''::character varying,
  agent_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  agent_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS agents_db_agent_name_idx ON public.agents_db (agent_name);

-- ===== Magazines =====
CREATE TABLE IF NOT EXISTS public.magazines_db (
  magazine_id VARCHAR(255) NOT NULL,
  magazine_name VARCHAR(255) NOT NULL,
  magazine_description TEXT NULL DEFAULT ''::text,
  magazine_starting_year INTEGER NULL,
  magazine_periodicity VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  magazine_subscriber_number INTEGER NULL,
  CONSTRAINT magazines_db_pkey PRIMARY KEY (magazine_id)
);

CREATE INDEX IF NOT EXISTS magazines_db_magazine_name_idx ON public.magazines_db (magazine_name);
CREATE INDEX IF NOT EXISTS magazines_db_magazine_starting_year_idx ON public.magazines_db (magazine_starting_year);

-- ===== Providers / invoices =====
CREATE TABLE IF NOT EXISTS public.providers_db (
  provider_id VARCHAR(255) PRIMARY KEY,
  provider_company_name VARCHAR(255) NOT NULL,
  provider_contact_email VARCHAR(255) NULL DEFAULT ''::character varying,
  provider_contact_phone VARCHAR(255) NULL DEFAULT ''::character varying,
  provider_full_address TEXT NULL DEFAULT ''::text,
  provider_tax_id VARCHAR(255) NULL DEFAULT ''::character varying,
  provider_notes TEXT NULL DEFAULT ''::text,
  provider_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  provider_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS providers_db_company_name_idx ON public.providers_db (provider_company_name);

CREATE OR REPLACE FUNCTION public.set_provider_invoices_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.invoice_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.provider_invoices_db (
  provider_invoice_id VARCHAR(255) PRIMARY KEY,
  provider_id VARCHAR(255) NOT NULL REFERENCES public.providers_db(provider_id) ON DELETE CASCADE,
  invoice_provider_reference_number VARCHAR(512) NOT NULL DEFAULT ''::character varying,
  provider_company_name VARCHAR(512) NOT NULL,
  invoice_amount_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
  invoice_issue_date DATE NOT NULL,
  invoice_payment_date DATE NOT NULL,
  invoice_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  invoice_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS provider_invoices_db_provider_idx ON public.provider_invoices_db (provider_id);
CREATE INDEX IF NOT EXISTS provider_invoices_db_payment_date_idx ON public.provider_invoices_db (invoice_payment_date);

DROP TRIGGER IF EXISTS provider_invoices_db_updated_at ON public.provider_invoices_db;
CREATE TRIGGER provider_invoices_db_updated_at
  BEFORE UPDATE ON public.provider_invoices_db
  FOR EACH ROW EXECUTE FUNCTION public.set_provider_invoices_updated_at();

-- ===== Proposals / contracts / projects (ProposalDbModel / ContractDbModel / ProjectDbModel) =====
CREATE OR REPLACE FUNCTION public.set_proposals_db_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.proposal_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.proposals_db (
  proposal_id VARCHAR(255) PRIMARY KEY,
  customer_id VARCHAR(255) NOT NULL,
  contact_id VARCHAR(255) NULL DEFAULT ''::character varying,
  additional_contact_ids_array TEXT[] NULL DEFAULT '{}'::text[],
  agent_id VARCHAR(255) NULL DEFAULT ''::character varying,
  proposal_status VARCHAR(255) NOT NULL,
  proposal_tittle VARCHAR(255) NOT NULL,
  proposal_ammount_eur NUMERIC(14,2) NULL DEFAULT 0,
  proposal_date DATE NULL,
  proposal_creation_date DATE NULL,
  proposal_expiration_date DATE NULL,
  proposal_general_discount NUMERIC(14,2) NULL DEFAULT 0,
  is_proposal_exchange BOOLEAN NULL DEFAULT false,
  exchange_has_final_price BOOLEAN NULL DEFAULT false,
  exchange_final_price NUMERIC(14,2) NULL DEFAULT 0,
  exchange_has_bank_transfers BOOLEAN NULL DEFAULT false,
  exchange_plynium_transfers_array TEXT[] NOT NULL DEFAULT '{}'::text[],
  exchange_counterpart_transfers_array TEXT[] NOT NULL DEFAULT '{}'::text[],
  proposal_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  proposal_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS proposals_db_customer_id_idx ON public.proposals_db (customer_id);
CREATE INDEX IF NOT EXISTS proposals_db_proposal_status_idx ON public.proposals_db (proposal_status);
CREATE INDEX IF NOT EXISTS proposals_db_agent_id_idx ON public.proposals_db (agent_id);
CREATE INDEX IF NOT EXISTS proposals_db_proposal_creation_date_idx ON public.proposals_db (proposal_creation_date);

CREATE TABLE IF NOT EXISTS public.proposal_service_lines (
  proposal_service_line_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id VARCHAR(255) NOT NULL REFERENCES public.proposals_db(proposal_id) ON DELETE CASCADE,
  service_id VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  proposal_service_custom_name VARCHAR(512) NOT NULL DEFAULT ''::character varying,
  proposal_service_discount NUMERIC(14, 2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS proposal_service_lines_proposal_id_idx ON public.proposal_service_lines (proposal_id);

CREATE TABLE IF NOT EXISTS public.proposal_payments (
  proposal_payment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id VARCHAR(255) NOT NULL REFERENCES public.proposals_db(proposal_id) ON DELETE CASCADE,
  proposal_payment_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  proposal_payment_date DATE NULL,
  proposal_payment_number VARCHAR(64) NOT NULL DEFAULT ''::character varying
);
CREATE INDEX IF NOT EXISTS proposal_payments_proposal_id_idx ON public.proposal_payments (proposal_id);

DROP TRIGGER IF EXISTS proposals_db_updated_at ON public.proposals_db;
CREATE TRIGGER proposals_db_updated_at
  BEFORE UPDATE ON public.proposals_db
  FOR EACH ROW EXECUTE FUNCTION public.set_proposals_db_updated_at();

CREATE TABLE IF NOT EXISTS public.contracts_db (
  id_contract VARCHAR(255) PRIMARY KEY,
  id_proposal VARCHAR(255) NOT NULL,
  id_customer VARCHAR(255) NOT NULL,
  agent VARCHAR(255) NULL DEFAULT ''::character varying,
  process_state VARCHAR(255) NOT NULL,
  payment_state VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  amount_eur NUMERIC(14,2) NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contracts_db_id_customer_idx ON public.contracts_db (id_customer);
CREATE INDEX IF NOT EXISTS contracts_db_id_proposal_idx ON public.contracts_db (id_proposal);
CREATE INDEX IF NOT EXISTS contracts_db_process_state_idx ON public.contracts_db (process_state);
CREATE INDEX IF NOT EXISTS contracts_db_payment_state_idx ON public.contracts_db (payment_state);
CREATE INDEX IF NOT EXISTS contracts_db_agent_idx ON public.contracts_db (agent);

CREATE TABLE IF NOT EXISTS public.projects_db (
  id_project VARCHAR(255) PRIMARY KEY,
  id_contract VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  service VARCHAR(255) NOT NULL,
  publication_date DATE NULL,
  publication_id VARCHAR(255) NULL,
  pm_events_array TEXT[] NULL DEFAULT '{}'::text[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS projects_db_id_contract_idx ON public.projects_db (id_contract);
CREATE INDEX IF NOT EXISTS projects_db_status_idx ON public.projects_db (status);
CREATE INDEX IF NOT EXISTS projects_db_service_idx ON public.projects_db (service);
CREATE INDEX IF NOT EXISTS projects_db_publication_date_idx ON public.projects_db (publication_date);

-- ===== PM events (PmEventDbModel) =====
CREATE TABLE IF NOT EXISTS public.pm_events_db (
  id_event VARCHAR(255) PRIMARY KEY,
  id_project VARCHAR(255) NOT NULL,
  id_customer VARCHAR(255) NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  event_description TEXT NOT NULL DEFAULT ''::text,
  event_state VARCHAR(255) NOT NULL DEFAULT 'pending'::character varying,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pm_events_db_id_project_idx ON public.pm_events_db (id_project);
CREATE INDEX IF NOT EXISTS pm_events_db_id_customer_idx ON public.pm_events_db (id_customer);
CREATE INDEX IF NOT EXISTS pm_events_db_event_type_idx ON public.pm_events_db (event_type);
CREATE INDEX IF NOT EXISTS pm_events_db_date_idx ON public.pm_events_db (date);
CREATE INDEX IF NOT EXISTS pm_events_db_event_state_idx ON public.pm_events_db (event_state);

-- ===== Billing (IssuedInvoiceDbModel / OrderDbModel) =====
CREATE OR REPLACE FUNCTION public.set_issued_invoices_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.invoice_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.issued_invoices_db (
  invoice_id VARCHAR(255) PRIMARY KEY,
  contract_id VARCHAR(255) NULL,
  customer_id VARCHAR(255) NOT NULL,
  customer_company VARCHAR(255) NOT NULL,
  agent_id VARCHAR(255) NULL DEFAULT ''::character varying,
  invoice_amount_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
  invoice_issue_date DATE NOT NULL,
  invoice_payment_date DATE NULL,
  invoice_state VARCHAR(255) NULL DEFAULT ''::character varying,
  invoice_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  invoice_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS issued_invoices_db_contract_id_idx ON public.issued_invoices_db (contract_id);
CREATE INDEX IF NOT EXISTS issued_invoices_db_customer_id_idx ON public.issued_invoices_db (customer_id);
CREATE INDEX IF NOT EXISTS issued_invoices_db_issue_date_idx ON public.issued_invoices_db (invoice_issue_date);
CREATE INDEX IF NOT EXISTS issued_invoices_db_payment_date_idx ON public.issued_invoices_db (invoice_payment_date);
CREATE INDEX IF NOT EXISTS issued_invoices_db_invoice_state_idx ON public.issued_invoices_db (invoice_state);

DROP TRIGGER IF EXISTS issued_invoices_db_updated_at ON public.issued_invoices_db;
CREATE TRIGGER issued_invoices_db_updated_at
  BEFORE UPDATE ON public.issued_invoices_db
  FOR EACH ROW EXECUTE FUNCTION public.set_issued_invoices_updated_at();

CREATE TABLE IF NOT EXISTS public.orders_db (
  order_code VARCHAR(255) PRIMARY KEY,
  invoice_id VARCHAR(255) NOT NULL REFERENCES public.issued_invoices_db(invoice_id) ON DELETE CASCADE,
  id_contract VARCHAR(255) NULL,
  contract_code VARCHAR(255) NULL,
  client_id VARCHAR(255) NULL,
  client_name VARCHAR(255) NULL,
  agent VARCHAR(255) NULL,
  id_contact VARCHAR(255) NULL,
  collection_date DATE NOT NULL,
  payment_status VARCHAR(255) NOT NULL,
  amount_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS orders_db_invoice_id_idx ON public.orders_db (invoice_id);
CREATE INDEX IF NOT EXISTS orders_db_id_contract_idx ON public.orders_db (id_contract);
CREATE INDEX IF NOT EXISTS orders_db_client_id_idx ON public.orders_db (client_id);
CREATE INDEX IF NOT EXISTS orders_db_collection_date_idx ON public.orders_db (collection_date);
CREATE INDEX IF NOT EXISTS orders_db_payment_status_idx ON public.orders_db (payment_status);

-- ===== Services catalog (ServiceDbModel; sin timestamps) =====
CREATE TABLE IF NOT EXISTS public.services_db (
  id_service VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  service_type VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  display_name VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  description TEXT NOT NULL DEFAULT ''::text,
  service_description TEXT NOT NULL DEFAULT ''::text,
  tariff_price_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
  unit VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  delivery_days INTEGER NOT NULL DEFAULT 0,
  publication_date DATE NULL
);

CREATE INDEX IF NOT EXISTS services_db_name_idx ON public.services_db (name);
CREATE INDEX IF NOT EXISTS services_db_service_type_idx ON public.services_db (service_type);

-- ===== Panel tickets (NotificationDbModel / Comment / CompanyContent); tabla RDS: panel_tickets =====
CREATE TABLE IF NOT EXISTS public.panel_tickets (
  panel_ticket_id VARCHAR(255) NOT NULL,
  panel_ticket_type VARCHAR(255) NOT NULL,
  panel_ticket_category VARCHAR(255) NULL DEFAULT NULL::character varying,
  panel_ticket_state VARCHAR(255) NOT NULL DEFAULT 'pending'::character varying,
  panel_ticket_date TIMESTAMPTZ NULL,
  panel_ticket_brief_description TEXT NOT NULL DEFAULT ''::text,
  panel_ticket_full_description TEXT NOT NULL DEFAULT ''::text,
  panel_ticket_related_to_user_id_array TEXT[] NOT NULL DEFAULT '{}'::text[],
  panel_ticket_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  panel_ticket_updates_array JSONB NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT panel_tickets_pkey PRIMARY KEY (panel_ticket_id)
);

CREATE INDEX IF NOT EXISTS panel_tickets_panel_ticket_type_idx ON public.panel_tickets (panel_ticket_type);
CREATE INDEX IF NOT EXISTS panel_tickets_panel_ticket_state_idx ON public.panel_tickets (panel_ticket_state);
CREATE INDEX IF NOT EXISTS panel_tickets_panel_ticket_date_idx ON public.panel_tickets (panel_ticket_date);
CREATE INDEX IF NOT EXISTS panel_tickets_panel_ticket_category_idx ON public.panel_tickets (panel_ticket_category);

CREATE TABLE IF NOT EXISTS public.panel_ticket_comments (
  panel_ticket_comment_id SERIAL PRIMARY KEY,
  panel_ticket_id VARCHAR(255) NOT NULL REFERENCES public.panel_tickets (panel_ticket_id) ON DELETE CASCADE,
  agent_id VARCHAR(255) NULL REFERENCES public.agents_db (agent_id) ON DELETE SET NULL,
  panel_ticket_comment_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  panel_ticket_comment_content TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS panel_ticket_comments_panel_ticket_id_idx ON public.panel_ticket_comments (panel_ticket_id);
CREATE INDEX IF NOT EXISTS panel_ticket_comments_panel_ticket_comment_date_idx ON public.panel_ticket_comments (panel_ticket_comment_date);
CREATE INDEX IF NOT EXISTS panel_ticket_comments_agent_id_idx ON public.panel_ticket_comments (agent_id);

CREATE TABLE IF NOT EXISTS public.panel_ticket_company_data (
  ticket_company_data_id SERIAL PRIMARY KEY,
  ticket_id VARCHAR(255) NOT NULL REFERENCES public.panel_tickets (panel_ticket_id) ON DELETE CASCADE,
  ticket_company_name VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  ticket_company_tax_name VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  ticket_company_tax_id VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  ticket_company_creator_role VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  ticket_company_website VARCHAR(255) NULL DEFAULT ''::character varying,
  ticket_company_country VARCHAR(255) NULL DEFAULT ''::character varying,
  ticket_company_description TEXT NULL DEFAULT ''::text,
  CONSTRAINT panel_ticket_company_data_ticket_id_key UNIQUE (ticket_id)
);

CREATE TABLE IF NOT EXISTS public.user_notifications (
  user_notification_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users_db (user_id) ON DELETE CASCADE,
  notification_type VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  notification_content TEXT NOT NULL DEFAULT ''::text,
  notification_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  notification_status VARCHAR(64) NOT NULL DEFAULT 'pending'::character varying,
  notification_redirection VARCHAR(2048) NULL DEFAULT ''::character varying,
  CONSTRAINT user_notifications_pkey PRIMARY KEY (user_notification_id)
);

CREATE INDEX IF NOT EXISTS user_notifications_user_id_idx ON public.user_notifications (user_id);
CREATE INDEX IF NOT EXISTS user_notifications_notification_date_idx ON public.user_notifications (notification_date DESC);
CREATE INDEX IF NOT EXISTS user_notifications_notification_status_idx ON public.user_notifications (notification_status);
CREATE INDEX IF NOT EXISTS user_notifications_notification_type_idx ON public.user_notifications (notification_type);

-- ===== Publication workflow (publication_slots_db; offered_preferential_pages links optionally to a slot) =====
CREATE TABLE IF NOT EXISTS public.publication_slots_db (
  publication_slot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_id VARCHAR(255) NULL,
  publication_format VARCHAR(32) NOT NULL DEFAULT 'flipbook'::character varying,
  slot_key VARCHAR(32) NOT NULL,
  slot_content_type VARCHAR(32) NOT NULL,
  slot_state VARCHAR(32) NOT NULL DEFAULT 'pending'::character varying,
  customer_id VARCHAR(64) NULL,
  project_id VARCHAR(64) NULL,
  slot_media_url VARCHAR(512) NULL,
  slot_article_id VARCHAR(64) NULL,
  slot_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  slot_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT publication_slots_db_publication_format_check CHECK (publication_format IN ('flipbook', 'informer')),
  CONSTRAINT publication_slots_db_publication_id_fkey FOREIGN KEY (publication_id) REFERENCES public.publications_db (publication_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS publication_slots_db_publication_id_idx ON public.publication_slots_db (publication_id);
CREATE INDEX IF NOT EXISTS publication_slots_db_customer_id_idx ON public.publication_slots_db (customer_id);

-- ===== Publication slot content (ordered JSON objects per publication + slot) =====
CREATE TABLE IF NOT EXISTS public.publication_slot_content (
  publication_slot_content_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_id VARCHAR(255) NOT NULL,
  publication_slot_id INTEGER NOT NULL,
  publication_slot_position INTEGER NOT NULL DEFAULT 0,
  slot_content_format VARCHAR(64) NOT NULL DEFAULT ''::character varying,
  slot_content_object_array JSONB NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT publication_slot_content_publication_id_fkey
    FOREIGN KEY (publication_id) REFERENCES public.publications_db (publication_id) ON DELETE CASCADE,
  CONSTRAINT publication_slot_content_publication_slot_id_fkey
    FOREIGN KEY (publication_slot_id) REFERENCES public.publication_slots_db (publication_slot_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS publication_slot_content_publication_id_idx ON public.publication_slot_content (publication_id);
CREATE INDEX IF NOT EXISTS publication_slot_content_publication_slot_id_idx ON public.publication_slot_content (publication_slot_id);
CREATE INDEX IF NOT EXISTS publication_slot_content_pub_slot_pos_idx ON public.publication_slot_content (publication_id, publication_slot_id, publication_slot_position);

CREATE TABLE IF NOT EXISTS public.offered_preferential_pages (
  offered_page_id UUID NOT NULL DEFAULT gen_random_uuid(),
  publication_id VARCHAR(255) NULL,
  publication_slot_id INTEGER NULL,
  offered_page_type VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  offered_slot_key VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  agent_id VARCHAR(255) NULL,
  customer_id VARCHAR(255) NULL,
  proposal_id VARCHAR(255) NULL,
  offered_page_proposal_date DATE NULL,
  CONSTRAINT offered_preferential_pages_pkey PRIMARY KEY (offered_page_id),
  CONSTRAINT offered_preferential_pages_publication_id_fkey
    FOREIGN KEY (publication_id) REFERENCES public.publications_db (publication_id) ON DELETE SET NULL,
  CONSTRAINT offered_preferential_pages_publication_slot_id_fkey
    FOREIGN KEY (publication_slot_id) REFERENCES public.publication_slots_db (publication_slot_id) ON DELETE SET NULL,
  CONSTRAINT offered_preferential_pages_proposal_id_fkey
    FOREIGN KEY (proposal_id) REFERENCES public.proposals_db (proposal_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS offered_preferential_pages_publication_id_idx ON public.offered_preferential_pages (publication_id);
CREATE INDEX IF NOT EXISTS offered_preferential_pages_publication_slot_id_idx ON public.offered_preferential_pages (publication_slot_id);
CREATE INDEX IF NOT EXISTS offered_preferential_pages_proposal_id_idx ON public.offered_preferential_pages (proposal_id);

-- ===== Newsletter user lists (antes de newsletters: FK opcional) =====
CREATE TABLE IF NOT EXISTS public.newsletter_user_lists (
  newsletter_user_list_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  newsletter_user_list_name VARCHAR(255) NULL,
  newsletter_user_list_portals_array_id INTEGER[] NOT NULL DEFAULT '{}'::INTEGER[],
  newsletter_user_list_topic VARCHAR(255) NULL,
  newsletter_user_list_description TEXT NULL DEFAULT ''::text,
  newsletter_user_list_created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===== Newsletters (NewsletterDbService) =====
CREATE OR REPLACE FUNCTION public.set_newsletter_campaigns_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.newsletter_campaign_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.newsletter_campaigns (
  newsletter_campaign_id VARCHAR(255) PRIMARY KEY,
  newsletter_campaign_name VARCHAR(255) NOT NULL,
  newsletter_campaign_description TEXT NULL DEFAULT ''::text,
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE RESTRICT,
  newsletter_campaign TEXT NULL DEFAULT ''::text,
  content_theme VARCHAR(255) NULL DEFAULT ''::character varying,
  newsletter_campaign_publication_frequency VARCHAR(255) NOT NULL,
  newsletter_campaign_start_date DATE NULL,
  newsletter_campaign_end_date DATE NULL,
  newsletter_campaign_planned_publication_dates_array DATE[] NOT NULL DEFAULT '{}'::date[],
  newsletter_campaign_status VARCHAR(255) NOT NULL DEFAULT 'draft'::character varying,
  newsletter_campaign_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  newsletter_campaign_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS newsletter_campaigns_updated_at ON public.newsletter_campaigns;
CREATE TRIGGER newsletter_campaigns_updated_at
  BEFORE UPDATE ON public.newsletter_campaigns
  FOR EACH ROW EXECUTE FUNCTION public.set_newsletter_campaigns_updated_at();

CREATE OR REPLACE FUNCTION public.set_newsletters_db_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.newsletter_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.newsletters_db (
  newsletter_id VARCHAR(255) PRIMARY KEY,
  newsletter_campaign_id VARCHAR(255) NOT NULL REFERENCES public.newsletter_campaigns(newsletter_campaign_id) ON DELETE CASCADE,
  portal_id INTEGER NOT NULL REFERENCES public.portals_id(portal_id) ON DELETE RESTRICT,
  newsletter_estimated_publication_date DATE NULL,
  newsletter_real_publication_date DATE NULL,
  newsletter_topic VARCHAR(255) NULL DEFAULT ''::character varying,
  newsletter_status VARCHAR(255) NOT NULL DEFAULT 'pending'::character varying,
  newsletter_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  newsletter_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  newsletter_user_list_id_array UUID[] NULL
);

DROP TRIGGER IF EXISTS newsletters_db_updated_at ON public.newsletters_db;
CREATE TRIGGER newsletters_db_updated_at
  BEFORE UPDATE ON public.newsletters_db
  FOR EACH ROW EXECUTE FUNCTION public.set_newsletters_db_updated_at();

CREATE INDEX IF NOT EXISTS newsletters_db_campaign_idx ON public.newsletters_db (newsletter_campaign_id);
CREATE INDEX IF NOT EXISTS newsletters_db_estimated_pub_idx ON public.newsletters_db (newsletter_estimated_publication_date);

CREATE OR REPLACE FUNCTION public.set_newsletter_content_blocks_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.newsletter_block_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.newsletter_content_blocks (
  newsletter_block_id VARCHAR(255) NOT NULL,
  newsletter_id VARCHAR(255) NOT NULL REFERENCES public.newsletters_db(newsletter_id) ON DELETE CASCADE,
  newsletter_block_type VARCHAR(255) NOT NULL,
  newsletter_block_position INTEGER NOT NULL DEFAULT 0,
  newsletter_block_content JSONB NOT NULL DEFAULT '{}'::jsonb,
  newsletter_block_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  newsletter_block_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (newsletter_id, newsletter_block_id)
);

DROP TRIGGER IF EXISTS newsletter_content_blocks_updated_at ON public.newsletter_content_blocks;
CREATE TRIGGER newsletter_content_blocks_updated_at
  BEFORE UPDATE ON public.newsletter_content_blocks
  FOR EACH ROW EXECUTE FUNCTION public.set_newsletter_content_blocks_updated_at();

CREATE INDEX IF NOT EXISTS newsletter_content_blocks_newsletter_id_idx ON public.newsletter_content_blocks (newsletter_id);

-- ===== Revenues / payments (BanksForecastDbService) =====
CREATE OR REPLACE FUNCTION public.set_revenues_db_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.revenue_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.revenues_db (
  revenue_id VARCHAR(255) PRIMARY KEY,
  customer_id VARCHAR(255) NULL REFERENCES public.customers_db(customer_id) ON DELETE SET NULL,
  customer_name VARCHAR(255) NULL DEFAULT ''::character varying,
  revenue_label VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  revenue_reference VARCHAR(255) NULL DEFAULT ''::character varying,
  revenue_expected_amount_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
  revenue_real_amount_eur NUMERIC(14,2) NULL,
  revenue_expected_payment_date DATE NOT NULL,
  revenue_real_payment_date DATE NULL,
  revenue_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revenue_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS revenues_db_updated_at ON public.revenues_db;
CREATE TRIGGER revenues_db_updated_at
  BEFORE UPDATE ON public.revenues_db
  FOR EACH ROW EXECUTE FUNCTION public.set_revenues_db_updated_at();

CREATE INDEX IF NOT EXISTS revenues_db_customer_id_idx ON public.revenues_db (customer_id);
CREATE INDEX IF NOT EXISTS revenues_db_revenue_expected_payment_date_idx ON public.revenues_db (revenue_expected_payment_date);

CREATE OR REPLACE FUNCTION public.set_payments_db_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.payment_updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.payments_db (
  payment_id VARCHAR(255) PRIMARY KEY,
  provider_id VARCHAR(255) NULL REFERENCES public.providers_db(provider_id) ON DELETE SET NULL,
  payment_provider_name VARCHAR(255) NULL DEFAULT ''::character varying,
  payment_label VARCHAR(255) NOT NULL DEFAULT ''::character varying,
  payment_reference VARCHAR(255) NULL DEFAULT ''::character varying,
  payment_expected_amount_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
  payment_real_amount_eur NUMERIC(14,2) NULL,
  payment_expected_date DATE NOT NULL,
  payment_real_date DATE NULL,
  payment_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  payment_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS payments_db_updated_at ON public.payments_db;
CREATE TRIGGER payments_db_updated_at
  BEFORE UPDATE ON public.payments_db
  FOR EACH ROW EXECUTE FUNCTION public.set_payments_db_updated_at();

CREATE INDEX IF NOT EXISTS payments_db_provider_id_idx ON public.payments_db (provider_id);
CREATE INDEX IF NOT EXISTS payments_db_payment_expected_date_idx ON public.payments_db (payment_expected_date);

COMMIT;

