-- 066_topics_db_and_user_feed_preferences.sql
-- Tablas: topics_db (temas de contenido por portal) y user_feed_preferences (preferencias por usuario/tema).
-- Idempotente donde aplica (IF NOT EXISTS). Tras crear tablas, inserta temas iniciales para portal_id = 1.

BEGIN;

-- Temas de contenido (panel / feeds)
CREATE TABLE IF NOT EXISTS public.topics_db (
  topic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_portal INTEGER NOT NULL,
  topic_name VARCHAR(255) NOT NULL,
  topic_description TEXT NOT NULL DEFAULT ''::text,
  topic_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  topic_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT topics_db_topic_portal_fkey
    FOREIGN KEY (topic_portal) REFERENCES public.portals_db (portal_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS topics_db_topic_portal_idx ON public.topics_db (topic_portal);
CREATE INDEX IF NOT EXISTS topics_db_topic_name_idx ON public.topics_db (topic_name);
CREATE UNIQUE INDEX IF NOT EXISTS topics_db_portal_name_uidx ON public.topics_db (topic_portal, topic_name);

CREATE OR REPLACE FUNCTION public.set_topics_db_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.topic_updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS topics_db_set_updated_at ON public.topics_db;
CREATE TRIGGER topics_db_set_updated_at
  BEFORE UPDATE ON public.topics_db
  FOR EACH ROW
  EXECUTE FUNCTION public.set_topics_db_updated_at();

-- Preferencias de feed por usuario (portal / apps pueden poblar filas)
CREATE TABLE IF NOT EXISTS public.user_feed_preferences (
  user_feed_preference_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  topic_id INTEGER NOT NULL,
  preference_state VARCHAR(32) NOT NULL DEFAULT 'neutral'::character varying,
  CONSTRAINT user_feed_preferences_pkey PRIMARY KEY (user_feed_preference_id),
  CONSTRAINT user_feed_preferences_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users_db (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT user_feed_preferences_topic_id_fkey
    FOREIGN KEY (topic_id) REFERENCES public.topics_db (topic_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT user_feed_preferences_user_topic_key UNIQUE (user_id, topic_id),
  CONSTRAINT user_feed_preferences_state_chk CHECK (
    preference_state = ANY (
      ARRAY['neutral'::text, 'not interested'::text, 'very interested'::text]
    )
  )
);

CREATE INDEX IF NOT EXISTS user_feed_preferences_user_id_idx ON public.user_feed_preferences (user_id);
CREATE INDEX IF NOT EXISTS user_feed_preferences_topic_id_idx ON public.user_feed_preferences (topic_id);

-- Datos iniciales: listado de la captura (vidrio / industria), portal 1, timestamps del día de ejecución
INSERT INTO public.topics_db (topic_portal, topic_name, topic_description, topic_created_at, topic_updated_at)
SELECT 1, v.topic_name, ''::text, now(), now()
FROM (VALUES
  ('Architectural glass'),
  ('Automotive glass'),
  ('Container glass'),
  ('Decorative glass'),
  ('Energy-efficient glazing'),
  ('Flat glass'),
  ('Float glass'),
  ('Glass coatings'),
  ('Glass components'),
  ('Glass furnaces'),
  ('Glass insulation'),
  ('Glass machinery'),
  ('Glass raw materials'),
  ('Glass recycling'),
  ('Hollow glass'),
  ('Laminated glass'),
  ('Smart glass'),
  ('Solar glass'),
  ('Technical glass'),
  ('Tempered glass')
) AS v(topic_name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.topics_db t
  WHERE t.topic_portal = 1 AND t.topic_name = v.topic_name
);

COMMIT;
