-- 105_restore_publication_slots.sql
-- Restores public.publication_slots_db (removed in 103) and re-links offered_preferential_pages.publication_slot_id.

CREATE TABLE IF NOT EXISTS public.publication_slots_db (
  publication_slot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_id VARCHAR(255) NULL,
  publication_format VARCHAR(32) NOT NULL DEFAULT 'flipbook'::character varying,
  slot_key VARCHAR(32) NOT NULL,
  slot_content_type VARCHAR(32) NOT NULL,
  slot_state VARCHAR(32) NOT NULL DEFAULT 'pending'::character varying,
  customer_id VARCHAR(64) NULL,
  project_id VARCHAR(64) NULL,
  slot_media_url VARCHAR(512) NULL,
  slot_article_id VARCHAR(64) NULL,
  slot_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  slot_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT publication_slots_db_publication_format_check CHECK (publication_format IN ('flipbook', 'informer')),
  CONSTRAINT publication_slots_db_publication_id_fkey FOREIGN KEY (publication_id) REFERENCES public.publications_db (publication_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS publication_slots_db_publication_id_idx ON public.publication_slots_db (publication_id);
CREATE INDEX IF NOT EXISTS publication_slots_db_customer_id_idx ON public.publication_slots_db (customer_id);

ALTER TABLE public.offered_preferential_pages
  ADD COLUMN IF NOT EXISTS publication_slot_id INTEGER NULL;

ALTER TABLE public.offered_preferential_pages
  DROP CONSTRAINT IF EXISTS offered_preferential_pages_publication_slot_id_fkey;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'offered_preferential_pages_publication_slot_id_fkey'
  ) THEN
    ALTER TABLE public.offered_preferential_pages
      ADD CONSTRAINT offered_preferential_pages_publication_slot_id_fkey
      FOREIGN KEY (publication_slot_id) REFERENCES public.publication_slots_db (publication_slot_id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS offered_preferential_pages_publication_slot_id_idx ON public.offered_preferential_pages (publication_slot_id);
