-- 108_publication_slot_content.sql
-- Ordered content objects per publication + slot (see 065).

CREATE TABLE IF NOT EXISTS public.publication_slot_content (
  publication_slot_content_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_id VARCHAR(255) NOT NULL,
  publication_slot_id INTEGER NOT NULL,
  publication_slot_position INTEGER NOT NULL DEFAULT 0,
  slot_content_format VARCHAR(64) NOT NULL DEFAULT ''::character varying,
  slot_content_object_array JSONB NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT publication_slot_content_publication_id_fkey
    FOREIGN KEY (publication_id) REFERENCES public.publications_db (publication_id) ON DELETE CASCADE,
  CONSTRAINT publication_slot_content_publication_slot_id_fkey
    FOREIGN KEY (publication_slot_id) REFERENCES public.publication_slots_db (publication_slot_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS publication_slot_content_publication_id_idx ON public.publication_slot_content (publication_id);
CREATE INDEX IF NOT EXISTS publication_slot_content_publication_slot_id_idx ON public.publication_slot_content (publication_slot_id);
CREATE INDEX IF NOT EXISTS publication_slot_content_pub_slot_pos_idx ON public.publication_slot_content (publication_id, publication_slot_id, publication_slot_position);
